### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by red913** [Narwhalsss360/NTimer#1]
Everything worked fine 9 months ago, but I wanted to make some changes to my program and when compiling I got the following error. Any idea what is causing this? 

```
.pio\libdeps\nano_every\NTimer\src\NTimer.cpp:143:51: error: default argument given for parameter 2 of 'bool NTimer::start(uint8_t, uint8_t)'
 bool NTimer::start(uint8_t id, uint8_t call = ZERO)
                                                   ^
In file included from .pio\libdeps\nano_every\NTimer\src\NTimer.cpp:2:0:
Compiling .pio\build\nano_every\FrameworkArduino\wiring_digital.c.o
.pio\libdeps\nano_every\NTimer\src\NTimer.h:40:10: note: previous specification in 'bool NTimer::start(uint8_t, uint8_t)' here
     bool start(uint8_t, uint8_t = CALL);
          ^~~~~
```

**Comment by Narwhalsss360** [comment]
Hello! It looks like you're using commit 03389ff5.
### **What you could try to do:**
- Try to compile using the latest release commit which is tagged 1.2.0 on commit e2cffea2. 
- ***If*** you wrote your program according to 03389ff5, try to compile with commit eefbafe. It may work for you if you don't want to change any code, it does fix the issue (but it may not work, not a fully tested commit).

### Note:
***If you're not actually on commit 03389ff5, let me know which one you are on.***
